'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Building2, FolderPlus, Plus, Search } from 'lucide-react';
import { api, ApiRequestError } from '@/lib/api';
import { isAdmin } from '@/lib/auth';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Input } from '@/components/ui/Input';
import { Modal } from '@/components/ui/Modal';
import { SkeletonTable } from '@/components/ui/Skeleton';
import { useToast } from '@/components/ui/Toast';
import type { ClientRead, ClientStatus, ProjectCreate, ProjectRead, ProjectStatus } from '@/types';
import styles from './clients.module.css';
import ui from '@/components/ui/ui.module.css';

export default function ClientsPage() {
  const router=useRouter(),{showToast}=useToast();
  const[clients,setClients]=useState<ClientRead[]>([]),[projects,setProjects]=useState<ProjectRead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[clientOpen,setClientOpen]=useState(false),[projectOpen,setProjectOpen]=useState(false),[saving,setSaving]=useState(false);
  const[clientForm,setClientForm]=useState({name:'',contact_email:'',status:'lead' as ClientStatus});
  const[projectForm,setProjectForm]=useState<ProjectCreate>({name:'',code:'',client_id:'',status:'active',start_date:null,target_end_date:null});
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const[c,p]=await Promise.all([api.get<ClientRead[]>('/clients/?limit=100'),api.get<ProjectRead[]>('/assignments/projects?limit=100')]);setClients(c);setProjects(p)}catch(e){setError(e instanceof ApiRequestError?e.userMessage:'Unable to load clients.')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const filtered=useMemo(()=>clients.filter(c=>(!status||c.status===status)&&`${c.name} ${c.contact_email||''}`.toLowerCase().includes(query.toLowerCase())),[clients,query,status]);
  async function createClient(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api.post<ClientRead>('/clients/',{...clientForm,name:clientForm.name.trim(),contact_email:clientForm.contact_email.trim()||null});showToast('success','Client created.');setClientOpen(false);setClientForm({name:'',contact_email:'',status:'lead'});await load()}catch(err){showToast('error',err instanceof ApiRequestError?err.userMessage:'Unable to create client.')}finally{setSaving(false)}}
  async function createProject(e:React.FormEvent){e.preventDefault();if(!projectForm.client_id)return;setSaving(true);try{await api.post<ProjectRead>('/assignments/projects',{...projectForm,name:projectForm.name.trim(),code:projectForm.code.trim().toUpperCase()});showToast('success','Client project created.');setProjectOpen(false);setProjectForm({name:'',code:'',client_id:'',status:'active',start_date:null,target_end_date:null});await load()}catch(err){showToast('error',err instanceof ApiRequestError?err.userMessage:'Unable to create client project.')}finally{setSaving(false)}}
  if(error)return <ErrorState type="error" message={error} onRetry={load}/>;
  return <div className="fade-in">
    <div className={styles.header}><div><h2>Clients</h2><p>Customer portfolio, engagements, and delivery ownership.</p></div><div className={styles.headerRight}><span>{filtered.length} clients</span>{isAdmin()&&<><Button variant="secondary" size="sm" onClick={()=>setProjectOpen(true)}><FolderPlus size={16}/>Add client project</Button><Button size="sm" onClick={()=>setClientOpen(true)}><Plus size={16}/>Add client</Button></>}</div></div>
    <div className={styles.filters}><Input aria-label="Search clients" icon={<Search size={18}/>} placeholder="Search clients" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter client status" className={ui.selectField} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="lead">Lead</option><option value="inactive">Inactive</option></select></div>
    {loading?<SkeletonTable rows={5}/>:filtered.length===0?<EmptyState icon={<Building2/>} title="No clients found" description="Create a client to begin tracking its delivery portfolio."/>:<div className={styles.grid}>{filtered.map(c=>{const related=projects.filter(p=>p.client_id===c.id);return <button key={c.id} className={styles.clientCard} onClick={()=>router.push(`/clients/${c.id}`)}><div className={styles.cardTop}><span className={styles.icon}><Building2 size={19}/></span><span className={styles.status}>{c.status}</span></div><h3>{c.name}</h3><p>{c.contact_email||'No contact email'}</p><div className={styles.summary}><span><strong>{related.filter(p=>p.status==='active').length}</strong> active</span><span><strong>{related.length}</strong> projects</span></div></button>})}</div>}
    <Modal isOpen={clientOpen} onClose={()=>setClientOpen(false)} title="Add client"><form onSubmit={createClient}><div className={ui.formGrid}><Input label="Client name" required value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/><Input label="Contact email" type="email" value={clientForm.contact_email} onChange={e=>setClientForm({...clientForm,contact_email:e.target.value})}/><label className={ui.inputWrapper}><span className={ui.inputLabel}>Relationship status</span><select className={ui.selectField} value={clientForm.status} onChange={e=>setClientForm({...clientForm,status:e.target.value as ClientStatus})}><option value="lead">Lead</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className={ui.modalActions}><Button type="button" variant="ghost" onClick={()=>setClientOpen(false)}>Cancel</Button><Button type="submit" loading={saving}>Create client</Button></div></form></Modal>
    <Modal isOpen={projectOpen} onClose={()=>setProjectOpen(false)} title="Add client project"><form onSubmit={createProject}><div className={ui.formGrid}><label className={ui.inputWrapper}><span className={ui.inputLabel}>Client</span><select required className={ui.selectField} value={projectForm.client_id||''} onChange={e=>setProjectForm({...projectForm,client_id:e.target.value})}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Input label="Project name" required value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})}/><Input label="Project code" required value={projectForm.code} onChange={e=>setProjectForm({...projectForm,code:e.target.value.toUpperCase()})}/><label className={ui.inputWrapper}><span className={ui.inputLabel}>Status</span><select className={ui.selectField} value={projectForm.status} onChange={e=>setProjectForm({...projectForm,status:e.target.value as ProjectStatus})}><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option></select></label><div className={ui.formRow}><Input label="Start date" type="date" onChange={e=>setProjectForm({...projectForm,start_date:e.target.value||null})}/><Input label="Target end date" type="date" onChange={e=>setProjectForm({...projectForm,target_end_date:e.target.value||null})}/></div></div><div className={ui.modalActions}><Button type="button" variant="ghost" onClick={()=>setProjectOpen(false)}>Cancel</Button><Button type="submit" loading={saving}>Create project</Button></div></form></Modal>
  </div>;
}
